FROM python:3.12-slim AS base

# Install any additional OS packages you want in addition to sudo, git and nano
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,id=apt-cache \
    --mount=type=cache,target=/var/lib/apt,sharing=locked,id=apt-lib \
    apt-get update \
    && apt-get install -y --no-install-recommends \
    sudo git nano curl \
    g++ libmagic1 # required

WORKDIR /app

RUN mkdir -p /var/cache/pip

ENV PIP_CACHE_DIR=/var/cache/pip \
    PIP_ROOT_USER_ACTION=ignore

COPY pyproject.toml .

RUN --mount=type=cache,target=/var/cache/pip,sharing=locked,id=pip-cache \
    pip install --upgrade pip && pip install --config-settings="cmake.args=-DFETCH_ZLIB_NG=ON" .[prod]

COPY ./converter_app /app/converter_app

RUN --mount=type=cache,target=/var/cache/pip,sharing=locked,id=pip-cache \
    pip install --upgrade pip && pip install --config-settings="cmake.args=-DFETCH_ZLIB_NG=ON" .[prod]

RUN if [ -f .env.prod ]; then mv .env.prod .env; fi && \
    mkdir -p /var/log/chemotion-converter && \
    chmod a+wrx /var/log/chemotion-converter

ADD --chmod=755 https://github.com/ptrxyz/chemotion-bakery/raw/refs/heads/main/converter/pass /bin/genpass
RUN /bin/genpass chemotion chemotion > /app/htpasswd

ENV MAX_CONTENT_LENGTH=250M \
    GUNICORN_TIMEOUT=180 \
    PROFILES_DIR=/app/profiles \
    DATASETS_DIR=/app/datasets \
    HTPASSWD_PATH=/app/htpasswd

EXPOSE 4000

HEALTHCHECK --interval=5s --timeout=3s --start-period=5s --retries=3 \
    CMD curl --fail http://localhost:4000/ || exit 1

CMD ["gunicorn", "--bind=0.0.0.0:4000", "--preload", "converter_app.app:create_app()"]
# i.e. the command: gunicorn --bind=0.0.0.0:4000 --preload "converter_app.app:create_app()"

VOLUME [ "/app/profiles", "/app/datasets" ]