import logging

import requests
from flask import current_app

from converter_app.readers.helper.base import Reader
from converter_app.readers.helper.reader import Readers
from converter_app.readers.helper.asc_helper import AscHelper

logger = logging.getLogger(__name__)


class MsRawReader(Reader):
    """
    Reader uses MS raw files using the MS_CONVERTER
    """
    identifier = 'ms_raw_reader'
    priority = 10

    def __init__(self, file):
        super().__init__(file)

    # two or more chars in row

    def check(self):
        """
        :return: True if it fits
        """
        result = False

        if self.file.suffix.lower() == '.raw' and self.file.encoding == 'binary':
            parsed_url = current_app.config.get('MS_CONVERTER')
            files = {
                "main_file": (self.file.name, self.file.content, "image/x-panasonic-rw")
            }

            res = requests.post(parsed_url + 'msconvert_conversion', data={'test':''}, files=files, timeout=60)
            if res.status_code == 200:
                return True

        return result

    ###############################################################################
    # formatResultsElab
    ###############################################################################
    def format_results_chemotion(self, results):
        """
        Formats results (list of dictionaries) generated by the ALV parser for DLS
        data to fit metadata for eLabFTW.
        Renames metadata, ensures formats are correct.
        """
        metadata = {}
        data = {}

        # sample ID = Samplename
        metadata["Samplename"] = results[0]["Samplename"]
        # DLS device = Device Info --> options
        metadata["Device Info"] = results[0]["Device Info"].split("/")[0]
        # if results[0]['SampleMemo']:

        # solvent = nothing, needs to be filled in manually for dls (?)
        # sample volume [ml] = nothing, needs to be filled in manually for dls (?)
        metadata["wavelength [nm]"] = str(results[0]["Wavelength [nm]"])
        # measurement starting time --> earlierst "Date" in all the dates (don't hard code)
        time_obj = AscHelper.get_startdate(results)
        metadata["measurement starting time"] = str(time_obj['startdate_object'])

        data["duration [s]"] = time_obj['time_line']

        # relative time point [s] --> TODO ?
        # refractive index --> refractive index from LIST
        data["refractive index"] = AscHelper.list_values("Refractive Index", results)

        # temperature [K] --> Temperature [K] from LIST
        data["temperature [K]"] = AscHelper.list_values("Temperature [K]", results)

        # viscosity [mPas] --> Viscosity [cp] from LIST
        data["viscosity [mPas]"] = AscHelper.list_values("Viscosity [cp]", results)

        # detection angle [°] --> Angle [°] from LIST TODO decide on unit
        data["detection angle [degrees]"] = AscHelper.list_values("Angle [°]", results)

        # average diffusion coefficient [micron^2/s] --> Diffusion Coefficient 2. order fit [µm²/s] from LIST
        data["average diffusion coefficient [micron^2/s]"] = AscHelper.list_values(
            "Diffusion Coefficient 2. order fit [µm²/s]", results)

        # second cumulant (expansion parameter) --> Expansion Parameter µ2 from LIST
        data["second cumulant (expansion parameter)"] = AscHelper.list_values("Expansion Parameter µ2", results)

        # hydrodynamic radius [nm] --> Hydrodynamic Radius 2. order fit [nm]
        data["hydrodynamic radius [nm]"] = AscHelper.list_values("Hydrodynamic Radius 2. order fit [nm]", results)

        # average diffusion coefficient [micron^2/s] --> Diffusion Coefficient 2. order fit [µm²/s] from LIST
        data["average diffusion coefficient [micron^2/s]"] = AscHelper.list_values(
            "Diffusion Coefficient 2. order fit [µm²/s]", results)

        # second cumulant (expansion parameter) --> Expansion Parameter µ2 from LIST
        data["second cumulant (expansion parameter)"] = AscHelper.list_values("Expansion Parameter µ2", results)

        # hydrodynamic radius [nm] --> Hydrodynamic Radius 2. order fit [nm]
        data["hydrodynamic radius [nm]"] = AscHelper.list_values("Hydrodynamic Radius 2. order fit [nm]", results)

        for (key, val) in data.items():
            metadata[key] = AscHelper.str_vals(val)

        # duration [s] = Duration [s]
        metadata["duration [s]"] = str(results[0]["Duration [s]"])

        # first correlation delay [ms] TODO ?

        return {
            'data': data,
            'metadata': metadata
        }

    def prepare_tables(self):
        tables = []
        table = self.append_table(tables)

        return tables


Readers.instance().register(MsRawReader)
