import re

from converter_app.profile_migration import ProfileMigration


class ProfileMigrationScript(ProfileMigration):
    """
    Migrate and normalize a SEC (Size Exclusion Chromatography) profile definition
    to a loop-ready configuration compatible with the new multi-detector SEC reader.

    This method mutates the given profile dictionary in place and is intentionally
    non-idempotent (it marks already-processed profiles via a description suffix).

    Behavior overview:
    - Applies only to profiles whose metadata reader is "SecReader" and that have
      not yet been auto-migrated by the converter.
    - Distinguishes between legacy profiles with more than two tables (deprecated)
      and simpler profiles that can be auto-migrated.
    - For deprecated profiles:
      - Marks the profile as disabled.
      - Appends a deprecation notice to the description.
    - For migratable profiles:
      - Updates table column indices and configures loop header matching (ELU, MWD).
      - Sets a loop type to table-header–driven ("theader").
      - Normalizes detector-related metadata identifiers.
      - Auto-generates per-detector metadata identifiers (DECT1 – DECT5) for common SEC keys.
      - Enforces required file metadata identifiers (reader, extension).
      - Marks the profile as enabled and appends a migration notice.
    """

    def up(self, profile: dict):
        """
        Updates the profile.
        """
        if profile["data"]["metadata"].get("reader") == "SecReader" and "--autogenerated by converter app for SEC loop" not in profile["description"]:
            if len(profile["tables"]) > 2:
                profile["isDisabled"] = True
                profile["description"] = profile[
                                             "description"] + ("\n !deprecated please see the new loop ready profile." + "\n --autogenerated by converter app for SEC loop")
            else:
                profile["isDisabled"] = False
                profile["description"] = profile["description"] + ("\n !migrated for new SEC (all detectors) loop ready reader."
                                                                   " Please check if is still correct." + "\n --autogenerated by converter app for SEC loop")
                profile["tables"][0]["table"]["xColumn"]["tableIndex"] = 6
                profile["tables"][0]["table"]["yColumn"]["tableIndex"] = 6
                profile["tables"][0]["loopType"] = "theader"
                profile["tables"][0]["table"]["loop_theader"] = [
                    {
                        "ignore_missing_values": False,
                        "line": "1",
                        "operator": "&",
                        "regex": "ELU",
                        "table": "0",
                        "type": "header_value",
                    }
                ]
                if len(profile["tables"]) >= 2:
                    profile["tables"][1]["table"]["xColumn"]["tableIndex"] = 7
                    profile["tables"][1]["table"]["yColumn"]["tableIndex"] = 7
                    profile["tables"][1]["loopType"] = "theader"
                    profile["tables"][1]["table"]["loop_theader"] = [
                        {
                            "ignore_missing_values": False,
                            "line": "1",
                            "operator": "&",
                            "regex": "MWD",
                            "table": "0",
                            "type": "header_value",
                        }
                    ]
                profile["identifiers"] = [d for d in profile["identifiers"] if d.get("optional") is True]
                for d in profile["identifiers"]:
                    if "outputTableIndex" in d:
                        d["outputTableIndex"] = None
                    if d.get("outputKey") in {"no_dec", "no_detec", "no_detectors", "number_of_detectors"}:
                        d["match"] = "any"
                        d["value"] = ""
                        d["key"] = "Number of detectors"
                        d["outputTableIndex"] = None
                        d["tableIndex"] = 0
                        d["type"] = "tableMetadata"
                for i in range(1, 6):
                    for key in ["A","D","M(z+1)","Mn","Mp","Mv","Mw","Mz","Vp","[n]"]:
                        profile["identifiers"].append(
                            {
                                "editable": True,
                                "id": f"autogen_{key}_DECT{i}",
                                "key": f"{key}_DECT{i}",
                                "match": "any",
                                "optional": True,
                                "outputKey": f"{clean_string(key)}",
                                "outputLayer": f"eval_data_detec_{i}",
                                "outputTableIndex": None,
                                "tableIndex": 0,
                                "type": "tableMetadata",
                                "value": ""
                            })
                profile["identifiers"].append(
                    {
                        "editable": True,
                        "id": "#2a7efd32-69e5-4a4d-9e3e-dd354d5fb298",
                        "key": "reader",
                        "match": "exact",
                        "optional": False,
                        "type": "fileMetadata",
                        "value": "SecReader"
                    })
                profile["identifiers"].append(
                    {
                        "editable": True,
                        "id": "#0382d500-5dea-4eff-8973-cd88a0453f81",
                        "key": "extension",
                        "match": "regex",
                        "optional": False,
                        "type": "fileMetadata",
                        "value": "\\.(txt|TXT)$"
                    })


    def to_be_applied_after_migration(self) -> str:
        """
        Uses the unique identifier of the last script to tell the migration process in which order
        the migration script must be applied.
        """

        return '20251119072527'

    @property
    def identifier(self):
        """
        A unique identifier for the migration script.
        This identifier will be used:
         A) in the Profile to determine if a migration has been applied to a certain Profile.
         B) must be returned by the to_be_applied_after_migration method of the following script
        """

        return '20260113143334'

def clean_string(s: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]+", "", s).lower()