from pathlib import Path

from test_static.utils import TestReader


def test_bio_logic():
    test_file = Path(
        __file__).parent.parent / 'test_static/test_files/bio_logic_FK155_JLGU_GE_50-2_15_m1p233mg_Li_LP30_RT_rate_stability_20230906.tar.xz'
    with TestReader(test_file.__str__(), 'bio_logic_080ecac4-8fa2-4c47-b7cc-4ef5db082b07') as reader:
        tables = reader.as_dict['tables']
        assert tables[-1]['header'] == ['EC-Lab LOG FILE', 'Galvanostatic Cycling with Potential Limitation',
                                        'CE vs. WE compliance from -10 V to 10 V',
                                        'EC-Lab for windows v11.43 (software)', 'Internet server v11.40 (firmware)',
                                        'Command interpretor v11.40 (firmware)']

        assert tables[-1]['metadata'] == {"Run on channel": "7 (SN 67339)",
                                          "Electrode connection": "standard",
                                          "Potential control": "Ewe",
                                          "Ewe ctrl range": "min = -10.00 V, max = 10.00 V",
                                          "Safety Limits": "Do not start on E overload",
                                          "Acquisition started on": "09/06/2023 15:18:20.995",
                                          "Loaded Setting File": "D:\\Fabian\\LiBOB in EiPS\\Graphite half cell\\FK125_JLGU_GE_LP30_RateAndCyclab_1p26mg_PlOldPress_090823\\FK125_JLGU_GE_LP30_RateAndCyclab_1p26mg_PlOldPress_090823.mps",
                                          "Saved on.File": "FK155_JLGU_GE_50-2_15_m1p233mg_Li_LP30_RT_rate_stability_20230906_03_GCPL_C07.mpr",
                                          "Saved on.Directory": "D:\\Fabian\\LiBOB in EiPS\\Graphite half cell\\FK155_JLGU_GE_50-2_15_m1p233mg_Li_LP30_RT_rate_stability_20230906\\",
                                          "Saved on.Host": "192.109.209.100",
                                          "Device": "MPG-2 (SN 0328)",
                                          "Address": "192.109.209.99",
                                          "Electrode material": "GE (S\u00fcdchemie)",
                                          "Initial state": "discharged",
                                          "Electrolyte": "LP30",
                                          "Comments": "rate + cyclability",
                                          "Mass of active material": "1.260 mg",
                                          "at x": "0.000",
                                          "Molecular weight of active material (at x = 0)": "0.001 g/mol",
                                          "Atomic weight of intercalated ion": "0.001 g/mol",
                                          "Acquisition started at": "xo = 0.000",
                                          "Number of e- transfered per intercalated ion": "1",
                                          "for DX": "1",
                                          "DQ": "33769.888 mA.h",
                                          "Battery capacity": "0.458 mA.h",
                                          "Reference electrode": "Li/Li+ (3.050 V)",
                                          "Electrode surface area": "1.130 cm\u00b2",
                                          "Characteristic mass": "1.260 mg",
                                          "Volume (V)": "0.001 cm\u00b3",
                                          "Cycle Definition": "Charge/Discharge alternance",
                                          "Ns [COLUMN: 0]": "0",
                                          "Ns [COLUMN: 1]": "1",
                                          "Ns [COLUMN: 2]": "2",
                                          "Ns": "[0,1,2]",
                                          "Set I/C [COLUMN: 0]": "I",
                                          "Set I/C [COLUMN: 1]": "C x N",
                                          "Set I/C [COLUMN: 2]": "C x N",
                                          "Set I/C": "[I,C x N,C x N]",
                                          "Is [COLUMN: 0]": "0.000",
                                          "Is [COLUMN: 1]": "10.000",
                                          "Is [COLUMN: 2]": "-10.000",
                                          "Is": "[0.000,10.000,-10.000]",
                                          "unit Is [COLUMN: 0]": "mA",
                                          "unit Is [COLUMN: 1]": "mA",
                                          "unit Is [COLUMN: 2]": "mA",
                                          "unit Is": "[mA,mA,mA]",
                                          "vs. [COLUMN: 0]": "<None>",
                                          "vs. [COLUMN: 1]": "<None>",
                                          "vs. [COLUMN: 2]": "<None>",
                                          "vs.": "[<None>,<None>,<None>]",
                                          "N [COLUMN: 0]": "1.00",
                                          "N [COLUMN: 1]": "0.10",
                                          "N [COLUMN: 2]": "0.10",
                                          "N": "[1.00,0.10,0.10]",
                                          "I sign [COLUMN: 0]": "< 0",
                                          "I sign [COLUMN: 1]": "< 0",
                                          "I sign [COLUMN: 2]": "> 0",
                                          "I sign": "[< 0,< 0,> 0]",
                                          "t1 (h:m:s) [COLUMN: 0]": "0:00:0.0000",
                                          "t1 (h:m:s) [COLUMN: 1]": "20:00:0.0000",
                                          "t1 (h:m:s) [COLUMN: 2]": "20:00:0.0000",
                                          "t1 (h:m:s)": "[0:00:0.0000,20:00:0.0000,20:00:0.0000]",
                                          "I Range [COLUMN: 0]": "100 \u00b5A",
                                          "I Range [COLUMN: 1]": "100 \u00b5A",
                                          "I Range [COLUMN: 2]": "100 \u00b5A",
                                          "I Range": "[100 \u00b5A,100 \u00b5A,100 \u00b5A]",
                                          "Bandwidth [COLUMN: 0]": "5",
                                          "Bandwidth [COLUMN: 1]": "5",
                                          "Bandwidth [COLUMN: 2]": "5",
                                          "Bandwidth": "[5,5,5]",
                                          "dE1 (mV) [COLUMN: 0]": "0.00",
                                          "dE1 (mV) [COLUMN: 1]": "10.00",
                                          "dE1 (mV) [COLUMN: 2]": "10.00",
                                          "dE1 (mV)": "[0.00,10.00,10.00]",
                                          "dt1 (s) [COLUMN: 0]": "0.0000",
                                          "dt1 (s) [COLUMN: 1]": "10.0000",
                                          "dt1 (s) [COLUMN: 2]": "10.0000",
                                          "dt1 (s)": "[0.0000,10.0000,10.0000]",
                                          "EM (V) [COLUMN: 0]": "0.000",
                                          "EM (V) [COLUMN: 1]": "0.005",
                                          "EM (V) [COLUMN: 2]": "2.000",
                                          "EM (V)": "[0.000,0.005,2.000]",
                                          "tM (h:m:s) [COLUMN: 0]": "0:00:0.0000",
                                          "tM (h:m:s) [COLUMN: 1]": "0:00:0.0000",
                                          "tM (h:m:s) [COLUMN: 2]": "0:00:0.0000",
                                          "tM (h:m:s)": "[0:00:0.0000,0:00:0.0000,0:00:0.0000]",
                                          "Im [COLUMN: 0]": "0.000",
                                          "Im [COLUMN: 1]": "0.000",
                                          "Im [COLUMN: 2]": "0.000",
                                          "Im": "[0.000,0.000,0.000]",
                                          "unit Im [COLUMN: 0]": "mA",
                                          "unit Im [COLUMN: 1]": "mA",
                                          "unit Im [COLUMN: 2]": "mA",
                                          "unit Im": "[mA,mA,mA]",
                                          "dI/dt [COLUMN: 0]": "0.000",
                                          "dI/dt [COLUMN: 1]": "0.000",
                                          "dI/dt [COLUMN: 2]": "0.000",
                                          "dI/dt": "[0.000,0.000,0.000]",
                                          "dunit dI/dt [COLUMN: 0]": "mA/s",
                                          "dunit dI/dt [COLUMN: 1]": "mA/s",
                                          "dunit dI/dt [COLUMN: 2]": "mA/s",
                                          "dunit dI/dt": "[mA/s,mA/s,mA/s]",
                                          "E range min (V) [COLUMN: 0]": "-10.000",
                                          "E range min (V) [COLUMN: 1]": "-10.000",
                                          "E range min (V) [COLUMN: 2]": "-10.000",
                                          "E range min (V)": "[-10.000,-10.000,-10.000]",
                                          "E range max (V) [COLUMN: 0]": "10.000",
                                          "E range max (V) [COLUMN: 1]": "10.000",
                                          "E range max (V) [COLUMN: 2]": "10.000",
                                          "E range max (V)": "[10.000,10.000,10.000]",
                                          "dq [COLUMN: 0]": "0.000",
                                          "dq [COLUMN: 1]": "1.000",
                                          "dq [COLUMN: 2]": "1.000",
                                          "dq": "[0.000,1.000,1.000]",
                                          "unit dq [COLUMN: 0]": "mA.h",
                                          "unit dq [COLUMN: 1]": "mA.h",
                                          "unit dq [COLUMN: 2]": "mA.h",
                                          "unit dq": "[mA.h,mA.h,mA.h]",
                                          "dtq (s) [COLUMN: 0]": "0.0000",
                                          "dtq (s) [COLUMN: 1]": "120.0000",
                                          "dtq (s) [COLUMN: 2]": "120.0000",
                                          "dtq (s)": "[0.0000,120.0000,120.0000]",
                                          "dQM [COLUMN: 0]": "0.000",
                                          "dQM [COLUMN: 1]": "0.000",
                                          "dQM [COLUMN: 2]": "0.000",
                                          "dQM": "[0.000,0.000,0.000]",
                                          "unit dQM [COLUMN: 0]": "mA.h",
                                          "unit dQM [COLUMN: 1]": "mA.h",
                                          "unit dQM [COLUMN: 2]": "mA.h",
                                          "unit dQM": "[mA.h,mA.h,mA.h]",
                                          "dxM [COLUMN: 0]": "0.000",
                                          "dxM [COLUMN: 1]": "0.000",
                                          "dxM [COLUMN: 2]": "0.000",
                                          "dxM": "[0.000,0.000,0.000]",
                                          "delta SoC (%) [COLUMN: 0]": "pass",
                                          "delta SoC (%) [COLUMN: 1]": "pass",
                                          "delta SoC (%) [COLUMN: 2]": "pass",
                                          "delta SoC (%)": "[pass,pass,pass]",
                                          "tR (h:m:s) [COLUMN: 0]": "0:00:10.0000",
                                          "tR (h:m:s) [COLUMN: 1]": "0:00:0.0000",
                                          "tR (h:m:s) [COLUMN: 2]": "0:00:0.0000",
                                          "tR (h:m:s)": "[0:00:10.0000,0:00:0.0000,0:00:0.0000]",
                                          "dER/dt (mV/h) [COLUMN: 0]": "0.0",
                                          "dER/dt (mV/h) [COLUMN: 1]": "0.1",
                                          "dER/dt (mV/h) [COLUMN: 2]": "0.1",
                                          "dER/dt (mV/h)": "[0.0,0.1,0.1]",
                                          "dER (mV) [COLUMN: 0]": "0.00",
                                          "dER (mV) [COLUMN: 1]": "0.00",
                                          "dER (mV) [COLUMN: 2]": "0.00",
                                          "dER (mV)": "[0.00,0.00,0.00]",
                                          "dtR (s) [COLUMN: 0]": "1.0000",
                                          "dtR (s) [COLUMN: 1]": "120.0000",
                                          "dtR (s) [COLUMN: 2]": "120.0000",
                                          "dtR (s)": "[1.0000,120.0000,120.0000]",
                                          "EL (V) [COLUMN: 0]": "pass",
                                          "EL (V) [COLUMN: 1]": "4.200",
                                          "EL (V) [COLUMN: 2]": "3.500",
                                          "EL (V)": "[pass,4.200,3.500]",
                                          "goto Ns' [COLUMN: 0]": "0",
                                          "goto Ns' [COLUMN: 1]": "0",
                                          "goto Ns' [COLUMN: 2]": "1",
                                          "goto Ns'": "[0,0,1]",
                                          "nc cycles [COLUMN: 0]": "0",
                                          "nc cycles [COLUMN: 1]": "0",
                                          "nc cycles [COLUMN: 2]": "4",
                                          "nc cycles": "[0,0,4]",
                                          "Modify on": "09/19/2023 12:11",
                                          "rows": "0",
                                          "columns": "0"}

        assert len(tables[0]['rows']) == 16154
        assert tables[0]['columns'] == [{"key": "0", "name": "uts (s)"}, {"key": "1", "name": "Ns"},
                                        {"key": "2", "name": "time (s)"},
                                        {"key": "3", "name": "time standard_error (s)"},
                                        {"key": "4", "name": "dq (mA\u00b7h)"},
                                        {"key": "5", "name": "dq standard_error (mA\u00b7h)"},
                                        {"key": "6", "name": "(Q-Qo) (mA\u00b7h)"},
                                        {"key": "7", "name": "(Q-Qo) standard_error (mA\u00b7h)"},
                                        {"key": "8", "name": "Ewe (V)"}, {"key": "9", "name": "Ewe standard_error (V)"},
                                        {"key": "10", "name": "I Range"},
                                        {"key": "11", "name": "Q charge or discharge (C)"},
                                        {"key": "12", "name": "Q charge or discharge standard_error (C)"},
                                        {"key": "13", "name": "half cycle"}, {"key": "14", "name": "mode"},
                                        {"key": "15", "name": "ox or red"}, {"key": "16", "name": "error"},
                                        {"key": "17", "name": "control changes"}, {"key": "18", "name": "Ns changes"},
                                        {"key": "19", "name": "counter inc."}, {"key": "20", "name": "control_V (V)"},
                                        {"key": "21", "name": "control_V standard_error (V)"},
                                        {'key': '22', 'name': 'control_I (mA)'},
                                        {'key': '23', 'name': 'control_I standard_error (mA)'}]

        assert tables[0]['metadata'] == {"___TABLE_NAME__": "/", "settings.technique": "GCPL",
                                         "settings.comments": "60\u00b0C\r\nrate + cyclability",
                                         "settings.active_material_mass": "1.2599999904632568", "settings.at_x": "0.0",
                                         "settings.molecular_weight": "0.0010000000474974513",
                                         "settings.atomic_weight": "0.0010000000474974513",
                                         "settings.acquisition_start": "0.0", "settings.e_transferred": "1",
                                         "settings.electrode_material": "GE (S\u00fcdchemie)",
                                         "settings.electrolyte": "LP30",
                                         "settings.electrode_area": "1.1299999952316284",
                                         "settings.reference_electrode": "Li/Li+",
                                         "settings.characteristic_mass": "1.2599999904632568",
                                         "settings.battery_capacity": "0.4580000042915344",
                                         "settings.battery_capacity_unit": "1", "log.channel_number": "6",
                                         "log.channel_sn": "1803", "log.Ewe_ctrl_min": "-10.0",
                                         "log.Ewe_ctrl_max": "10.0", "log.ole_timestamp": "45175.637742997686",
                                         "log.filename": "D:\\Fabian\\LiBOB in EiPS\\Graphite half cell\\FK155_JLGU_GE_50-2_15_m1p233mg_Li_LP30_RT_rate_stability_20230906\\FK155_JLGU_GE_50-2_15_m1p233mg_Li_LP30_RT_rate_stability_20230906_02_GCPL_C07.mpr",
                                         "log.host": "192.109.209.100", "log.address": "192.109.209.99",
                                         "log.ec_lab_version": "11.43", "log.server_version": "11.40",
                                         "log.interpreter_version": "11.40", "log.device_sn": "0328",
                                         "log.averaging_points": "0", "params.Set I/C.0": "I",
                                         'params.Set I/C.1': 'C x N', 'params.Set I/C.2': 'C x N',
                                         "params.Is.0": "0.0", "params.Is.1": "-0.03700000047683716",
                                         "params.Is.2": "0.03700000047683716", "params.unit Is.0": "mA",
                                         "params.unit Is.1": "mA", "params.unit Is.2": "mA",
                                         "params.unit Is vs..0": "<None>", "params.unit Is vs..1": "<None>",
                                         "params.unit Is vs..2": "<None>", "params.N.0": "1.0",
                                         "params.N.1": "0.05000000074505806", "params.N.2": "0.05000000074505806",
                                         "params.I sign.0": "1", "params.I sign.1": "1", "params.I sign.2": "0",
                                         "params.t1 (h:m:s).0": "0.0", "params.t1 (h:m:s).1": "3600000.0",
                                         "params.t1 (h:m:s).2": "3600000.0", "params.I Range.0": "100 \u00b5A",
                                         "params.I Range.1": "10 \u00b5A", "params.I Range.2": "10 \u00b5A",
                                         "params.Bandwidth.0": "5", "params.Bandwidth.1": "5",
                                         "params.Bandwidth.2": "5", "params.dE1 (mV).0": "0.0",
                                         "params.dE1 (mV).1": "10.0", "params.dE1 (mV).2": "10.0",
                                         "params.dt1 (s).0": "0.0", "params.dt1 (s).1": "10.0",
                                         "params.dt1 (s).2": "10.0", "params.EM (V).0": "0.0",
                                         "params.EM (V).1": "0.004999999888241291", "params.EM (V).2": "2.0",
                                         "params.tM (h:m:s).0": "0.0", "params.tM (h:m:s).1": "0.0",
                                         "params.tM (h:m:s).2": "0.0", "params.Im.0": "0.0", "params.Im.1": "0.0",
                                         "params.Im.2": "0.0", "params.unit Im.0": "mA", "params.unit Im.1": "mA",
                                         "params.unit Im.2": "mA", "params.dI/dt.0": "0.0", "params.dI/dt.1": "0.0",
                                         "params.dI/dt.2": "0.0", "params.dunit dI/dt.0": "1",
                                         "params.dunit dI/dt.1": "1", "params.dunit dI/dt.2": "1",
                                         "params.E range min (V).0": "-10.0", "params.E range min (V).1": "-10.0",
                                         "params.E range min (V).2": "-10.0", "params.E range max (V).0": "10.0",
                                         "params.E range max (V).1": "10.0", "params.E range max (V).2": "10.0",
                                         "params.dq.0": "0.0", "params.dq.1": "1.0", "params.dq.2": "1.0",
                                         "params.unit dq.0": "mA.h", "params.unit dq.1": "mA.h",
                                         "params.unit dq.2": "mA.h", "params.dtq (s).0": "0.0",
                                         "params.dtq (s).1": "120.0", "params.dtq (s).2": "120.0",
                                         "params.dQM.0": "0.0", "params.dQM.1": "0.0", "params.dQM.2": "0.0",
                                         "params.unit dQM.0": "mA.h", "params.unit dQM.1": "mA.h",
                                         "params.unit dQM.2": "mA.h", "params.dxM.0": "0.0", "params.dxM.1": "0.0",
                                         "params.dxM.2": "0.0", "params.delta SoC (%).0": "nan",
                                         "params.delta SoC (%).1": "nan", "params.delta SoC (%).2": "nan",
                                         "params.tR (h:m:s).0": "0.0", "params.tR (h:m:s).1": "0.0",
                                         "params.tR (h:m:s).2": "0.0", "params.dER/dt (mV/h).0": "0.0",
                                         "params.dER/dt (mV/h).1": "0.10000000149011612",
                                         "params.dER/dt (mV/h).2": "0.0", "params.dER (mV).0": "0.0",
                                         "params.dER (mV).1": "0.0", "params.dER (mV).2": "0.0",
                                         "params.dtR (s).0": "2.0", "params.dtR (s).1": "120.0",
                                         "params.dtR (s).2": "120.0", "params.EL (V).0": "nan",
                                         "params.EL (V).1": "4.199999809265137", "params.EL (V).2": "3.5",
                                         "params.goto Ns'.0": "0", "params.goto Ns'.1": "0", "params.goto Ns'.2": "0",
                                         "params.nc cycles.0": "0", "params.nc cycles.1": "0",
                                         "params.nc cycles.2": "0",
                                         'unit.coords.uts': 's',
                                         'unit.data_vars.(Q-Qo)': 'mA·h',
                                         'unit.data_vars.(Q-Qo)_std_err': 'mA·h',
                                         'unit.data_vars.Ewe': 'V',
                                         'unit.data_vars.Ewe_std_err': 'V',
                                         'unit.data_vars.Q charge or discharge': 'C',
                                         'unit.data_vars.Q charge or discharge_std_err': 'C',
                                         'unit.data_vars.control_I': 'mA',
                                         'unit.data_vars.control_I_std_err': 'mA',
                                         'unit.data_vars.control_V': 'V',
                                         'unit.data_vars.control_V_std_err': 'V',
                                         'unit.data_vars.dq': 'mA·h',
                                         'unit.data_vars.dq_std_err': 'mA·h',
                                         'unit.data_vars.time': 's',
                                         'unit.data_vars.time_std_err': 's',
                                         "rows": "16154", "columns": "24"}
