name: Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install wheel setuptools pip pybind11 --upgrade
          pip install -r ./requirements/dev.txt
          pip install pytest
      - name: Build tests
        run: |
          python test_manager/__init__.py -t -g -tp
      - name: Test readers with pytest
        run: |
          pytest -v ./test_manager/test_readers.py
      - name: Test profiles with pytest
        run: |
          pytest -v ./test_manager/test_profiles.py
      - name: Test static test
        run: |
          pytest -v ./test_static
