name: Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install -y libmagic1 file
          pip install --upgrade pip
          pip install ".[dev]"
      - name: Build tests
        run: |
          python -m test_manager -t -gt -tp
      - name: Test the code with pytest
        run: |
          pytest .
