DATA_TYPES = (
    'INFRARED SPECTRUM',
    'RAMAN SPECTRUM',
    'INFRARED PEAK TABLE',
    'INFRARED INTERFEROGRAM',
    'INFRARED TRANSFERED SPECTRUM',
    'NMR FID',
    'NMR SPECTRUM',
    'NMR PEAK TABLE',
    'NMP PEAK ASSIGNMENTS',
    'MASS SPECTRUM',
    'CONTINUOUS MASS SPECTRUM',
    'THERMOGRAVIMETRIC ANALYSIS',
    'TENSIOMETRY',
    'UV-VIS',
    'HPLC UV-VIS',
    'GEL PERMEATION CHROMATOGRAPHY',
    'CYCLIC VOLTAMMETRY',
    'X-RAY DIFFRACTION',
    'SINGLE CRYSTAL X-RAY DIFFRACTION',
    'SORPTION-DESORPTION MEASUREMENT',
    'SIZE EXCLUSION CHROMATOGRAPHY',
)

DATA_CLASSES = (
    'XYPOINTS',
    'XYDATA',
    'PEAK TABLE',
    'NTUPLES',
)

XUNITS = (
    '%',
    '1/CM',
    '2Theta',
    'DEGREES CELSIUS',
    'G/MOL',
    'HZ',
    'KILOGRAM',
    'MICROMETERS',
    'MILIMETERS',
    'MINUTES',
    'm/z',
    'MOLECULAR MASS / DA',
    'NANOMETERS',
    'SECONDS',
    'Voltage vs Ref'
)

YUNITS = (
    'ABSORBANCE',
    'Ampere',
    'ARBITRARY UNITS',
    'COUNTS',
    'DERIVATIVE WEIGHT',
    'Intensity',
    'KUBELKA-MUNK',
    'mAU',
    'N/M2',
    'Newton',
    'REFLECTANCE',
    'SIGNAL',
    'TRANSMITTANCE',
    'WEIGHT',
)

OPTIONS = {
    'DATA TYPE': DATA_TYPES,
    'DATA CLASS': DATA_CLASSES,
    'XUNITS': XUNITS,
    'YUNITS': YUNITS,
}
